language: python
env:
  - PYTHON_VERSION="3.5"
  # - PYTHON_VERSION="3.6"
# command to install dependencies
os:
  - linux
  - osx

install:
  # Install conda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - python -c "import nltk; nltk.download('stopwords'); nltk.download('punkt')"
  - pip install -r requirements.txt
  - pip install flake8
  - pip install nose

# command to run tests
script:
  - nosetests --exe
  - flake8
